import time
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print("Your new username is now 'USER'")
time.sleep(2)
print("I hope you like it")
print(" ")
time.sleep(2)
print(" ")
print(" ")
print(" ")
print("you can change your name later, you can also choose a name for me, if you want...")
time.sleep(1)
print(" ")
print(" ")
print("You can call me Ruby")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" PLEASE READ THIS TEXT!!!")
time.sleep(5)
print("This bot helps with your work; it can auto write, help get files back, give ideas, and work with you!")
print("loading...")
print(" ")
time.sleep(10)
## ^^this is a troll text BTW^^

from subprocess import call
call(["python", "python-helper.py"])
