import time
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print("Your new username is now 'USER'")
time.sleep(2)
print("I hope you like it")
time.sleep(5)
print("Start bot?")
print ("Yes/No")
choice = input("")

if choice == "yes":
    print("Set up started")
    from subprocess import call
    call(["python", "python-helper.py"])
if choice == "no":
    print("OK...")
    print("Booting Down")
    from subprocess import call
    call(["python", "python-helper.py"])
